resolver: nightly-2016-11-03
packages:
- pkg/hs/nauva
- pkg/hs/nauva-catalog
- pkg/hs/nauva-css
- pkg/hs/nauva-dev-server
- examples/playground/app
- examples/playground/server

extra-deps:
- snap-blaze-0.2.1.4
